### ISSUE TITLE
Привет! не запускается сайт!

### ISSUE THREAD

**Issue by alienkras** [anonymous33rus/wowlegions#3]
все сделал как написано в readme перебрал все версии апатча пхп и мускула
выдает вот такое, Parse error: syntax error, unexpected T_CLASS, expecting T_STRING or T_VARIABLE or '$' in D:\OpenServer\OSPanel\domains\localhost\public\index.php on line 8
я так подозреваю у меня что то не хватает
ПОМОГИ ПЛС!
вот на апач 2.4 пхп 5.6 Parse error: syntax error, unexpected '?' in D:\OpenServer\OSPanel\domains\localhost\vendor\laravel\framework\src\Illuminate\Foundation\helpers.php on line 233
redis 3.2 x64

**Comment by anonymous33rus** [comment]
Привет, нужно сменить версию PHP 7.1+

**Comment by alienkras** [comment]
не помогло 
Warning: require(D:\OpenServer\OSPanel\domains\localhost\wowlegions-master\vendor\composer/../barryvdh/laravel-debugbar/src/helpers.php): failed to open stream: No such file or directory in D:\OpenServer\OSPanel\domains\localhost\wowlegions-master\vendor\composer\autoload_real.php on line 66

Fatal error: require(): Failed opening required 'D:\OpenServer\OSPanel\domains\localhost\wowlegions-master\vendor\composer/../barryvdh/laravel-debugbar/src/helpers.php' (include_path='.;d:/openserver/ospanel/modules/php/PHP-7.2-x64;d:/openserver/ospanel/modules/php/PHP-7.2-x64/PEAR/pear') in D:\OpenServer\OSPanel\domains\localhost\wowlegions-master\vendor\composer\autoload_real.php on line 66

**Comment by anonymous33rus** [comment]
Ожидайте, сделаю фикс.

**Comment by alienkras** [comment]
хорошо спасибо
!!!!

**Comment by anonymous33rus** [comment]
Обновил.

**Comment by anonymous33rus** [comment]
Загрузил не достающие файлы.
