### ISSUE TITLE
Register does not work

### ISSUE THREAD

**Issue by DJBoxer** [anonymous33rus/wowlegions#6]
I have all setup and linked to MySQL including soap account.

when you enter details all is fine but no account is created in auth accounts or website user accounts and shows no errors?

**Comment by DJBoxer** [comment]
I just tested it on your demo site, that does not work either :/

**Comment by DJBoxer** [comment]
Actually registration only works from local host. when new member fills out details they cant complete form as the image upload uses fakepath?? so this needs to be fixed or removed or a default image used instead.

**Comment by anonymous33rus** [comment]
Updated, removed avatar at registration
